import type { Product, Category, Review, RevenueData } from "@/types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Bijoux",
    slug: "bijoux",
    description:
      "Bagues, colliers, bracelets et boucles d'oreilles en or et diamants",
    imageUrl: "/images/categories/bijoux.jpg",
    _count: { products: 124 },
  },
  {
    id: "cat-2",
    name: "Montres",
    slug: "montres",
    description: "Montres de haute horlogerie pour hommes et femmes",
    imageUrl: "/images/categories/montres.jpg",
    _count: { products: 57 },
  },
  {
    id: "cat-3",
    name: "Maroquinerie",
    slug: "maroquinerie",
    description: "Sacs, portefeuilles et ceintures en cuir pleine fleur",
    imageUrl: "/images/categories/maroquinerie.jpg",
    _count: { products: 72 },
  },
  {
    id: "cat-4",
    name: "Mode",
    slug: "mode",
    description: "Vêtements et accessoires de mode de luxe",
    imageUrl: "/images/categories/mode.jpg",
    _count: { products: 89 },
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Collier Étoile Dorée",
    slug: "collier-etoile-doree",
    description: "Collier en or 18 carats serti de diamants naturels.",
    longDescription: `Façonné à la main par nos artisans joailliers de la Haute Joaillerie parisienne, ce collier exceptionnel incarne l'essence du luxe contemporain.

Chaque diamant est soigneusement sélectionné pour sa clarté et son éclat, puis serti avec une précision millimétrée. La chaîne en or 18 carats est entièrement réalisée à la main, avec une attention particulière portée à chaque maillon.

Ce collier est livré dans notre écrin signature, accompagné de son certificat d'authenticité et d'un bracelet-cadeau.`,
    price: 1290,
    compareAtPrice: 1650,
    images: [
      {
        id: "img-1-1",
        url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&w=800&q=80",
        alt: "Collier Étoile Dorée - Vue principale",
        order: 0,
      },
      {
        id: "img-1-2",
        url: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&w=800&q=80",
        alt: "Collier Étoile Dorée - Détail",
        order: 1,
      },
      {
        id: "img-1-3",
        url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&w=800&q=80",
        alt: "Collier Étoile Dorée - Port",
        order: 2,
      },
      {
        id: "img-1-4",
        url: "https://images.unsplash.com/photo-1616615902536-4b4a2f678dee?auto=format&w=800&q=80",
        alt: "Collier Étoile Dorée - Écrin",
        order: 3,
      },
    ],
    category: CATEGORIES[0],
    categoryId: "cat-1",
    variants: [
      {
        id: "var-1-1",
        name: "Longueur",
        value: "38 cm",
        stock: 5,
        priceModifier: 0,
      },
      {
        id: "var-1-2",
        name: "Longueur",
        value: "42 cm",
        stock: 8,
        priceModifier: 0,
      },
      {
        id: "var-1-3",
        name: "Longueur",
        value: "45 cm",
        stock: 3,
        priceModifier: 50,
      },
      {
        id: "var-1-4",
        name: "Longueur",
        value: "50 cm",
        stock: 2,
        priceModifier: 80,
      },
    ],
    tags: ["or", "diamants", "collier", "bestseller", "cadeau"],
    rating: 4.9,
    reviewCount: 247,
    stock: 18,
    status: "ACTIVE",
    isFeatured: true,
    isNew: false,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2025-03-10"),
  },
  {
    id: "prod-2",
    name: "Montre Lumière Noire",
    slug: "montre-lumiere-noire",
    description: "Montre en titane noir avec mouvement automatique suisse.",
    longDescription: `La Montre Lumière Noire est le résultat de deux années de recherche et développement. Son boîtier en titane PVD noir de 40mm abrite un mouvement automatique suisse de haute précision, visible à travers le fond saphir transparent.

Le cadran en carbone forgé affiche une texture unique que chaque exemplaire possède en exclusivité. Les aiguilles appliquées Super-LumiNova garantissent une lisibilité parfaite en toutes conditions.`,
    price: 3450,
    compareAtPrice: undefined,
    images: [
      {
        id: "img-2-1",
        url: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&w=800&q=80",
        alt: "Montre Lumière Noire",
        order: 0,
      },
      {
        id: "img-2-2",
        url: "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&w=800&q=80",
        alt: "Détail cadran",
        order: 1,
      },
      {
        id: "img-2-3",
        url: "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?auto=format&w=800&q=80",
        alt: "Bracelet cuir",
        order: 2,
      },
    ],
    category: CATEGORIES[1],
    categoryId: "cat-2",
    variants: [
      {
        id: "var-2-1",
        name: "Bracelet",
        value: "Cuir noir",
        stock: 6,
        priceModifier: 0,
      },
      {
        id: "var-2-2",
        name: "Bracelet",
        value: "Acier titane",
        stock: 4,
        priceModifier: 200,
      },
      {
        id: "var-2-3",
        name: "Bracelet",
        value: "Caoutchouc",
        stock: 3,
        priceModifier: -100,
      },
    ],
    tags: ["montre", "titane", "automatique", "suisse", "tendance"],
    rating: 4.8,
    reviewCount: 189,
    stock: 13,
    status: "ACTIVE",
    isFeatured: true,
    isNew: false,
    createdAt: new Date("2024-03-20"),
    updatedAt: new Date("2025-04-15"),
  },
  {
    id: "prod-3",
    name: "Sac Cuir Milano",
    slug: "sac-cuir-milano",
    description: "Sac à main en cuir de veau pleine fleur fabriqué à Milan.",
    longDescription: `Le Sac Milano est conçu dans les ateliers milanais de nos partenaires artisans. Confectionné en cuir de veau pleine fleur tannage végétal, il développe une belle patine avec le temps.

La doublure en soie ivoire et les finitions en laiton doré à l'or fin témoignent de l'exigence de qualité qui préside à chaque étape de fabrication. Chaque sac est numéroté et accompagné d'un certificat de provenance.`,
    price: 1690,
    compareAtPrice: undefined,
    images: [
      {
        id: "img-3-1",
        url: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&w=800&q=80",
        alt: "Sac Milano noir",
        order: 0,
      },
      {
        id: "img-3-2",
        url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&w=800&q=80",
        alt: "Détail fermoir",
        order: 1,
      },
      {
        id: "img-3-3",
        url: "https://images.unsplash.com/photo-1614179818511-84e9fd512f95?auto=format&w=800&q=80",
        alt: "Intérieur du sac",
        order: 2,
      },
    ],
    category: CATEGORIES[2],
    categoryId: "cat-3",
    variants: [
      {
        id: "var-3-1",
        name: "Couleur",
        value: "Noir",
        stock: 10,
        priceModifier: 0,
      },
      {
        id: "var-3-2",
        name: "Couleur",
        value: "Camel",
        stock: 7,
        priceModifier: 0,
      },
      {
        id: "var-3-3",
        name: "Couleur",
        value: "Bordeaux",
        stock: 4,
        priceModifier: 0,
      },
    ],
    tags: ["sac", "cuir", "milan", "artisan", "nouveau"],
    rating: 4.7,
    reviewCount: 312,
    stock: 21,
    status: "ACTIVE",
    isFeatured: true,
    isNew: true,
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-05-01"),
  },
  {
    id: "prod-4",
    name: "Bague Saphir Royal",
    slug: "bague-saphir-royal",
    description: "Bague solitaire en or blanc 18K avec saphir de Ceylan.",
    longDescription: `Cette bague d'exception est ornée d'un saphir de Ceylan de 2,5 carats d'un bleu profond et intense, entouré d'un pavage de diamants brillants. Montée sur or blanc 18 carats rhodié, elle rayonne d'une lumière incomparable.`,
    price: 2150,
    compareAtPrice: 2800,
    images: [
      {
        id: "img-4-1",
        url: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&w=800&q=80",
        alt: "Bague saphir",
        order: 0,
      },
      {
        id: "img-4-2",
        url: "https://images.unsplash.com/photo-1611085583191-a3b181a88401?auto=format&w=800&q=80",
        alt: "Détail saphir",
        order: 1,
      },
    ],
    category: CATEGORIES[0],
    categoryId: "cat-1",
    variants: [
      {
        id: "var-4-1",
        name: "Taille",
        value: "50",
        stock: 2,
        priceModifier: 0,
      },
      {
        id: "var-4-2",
        name: "Taille",
        value: "52",
        stock: 4,
        priceModifier: 0,
      },
      {
        id: "var-4-3",
        name: "Taille",
        value: "54",
        stock: 3,
        priceModifier: 0,
      },
      {
        id: "var-4-4",
        name: "Taille",
        value: "56",
        stock: 1,
        priceModifier: 0,
      },
    ],
    tags: ["bague", "saphir", "or blanc", "diamants", "promo"],
    rating: 5.0,
    reviewCount: 94,
    stock: 10,
    status: "ACTIVE",
    isFeatured: false,
    isNew: false,
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2025-02-20"),
  },
  {
    id: "prod-5",
    name: "Bracelet Or Blanc Pavé",
    slug: "bracelet-or-blanc-pave",
    description: "Bracelet jonc en or blanc pavé de diamants.",
    longDescription: `Un bracelet jonc d'une finesse remarquable, entièrement serti de diamants brillants en serti pavé. Réalisé à la main dans notre atelier parisien.`,
    price: 890,
    compareAtPrice: undefined,
    images: [
      {
        id: "img-5-1",
        url: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&w=800&q=80",
        alt: "Bracelet or blanc",
        order: 0,
      },
    ],
    category: CATEGORIES[0],
    categoryId: "cat-1",
    variants: [
      {
        id: "var-5-1",
        name: "Taille",
        value: "S (16cm)",
        stock: 6,
        priceModifier: 0,
      },
      {
        id: "var-5-2",
        name: "Taille",
        value: "M (17cm)",
        stock: 9,
        priceModifier: 0,
      },
      {
        id: "var-5-3",
        name: "Taille",
        value: "L (18cm)",
        stock: 4,
        priceModifier: 0,
      },
    ],
    tags: ["bracelet", "or blanc", "diamants", "nouveau"],
    rating: 4.6,
    reviewCount: 156,
    stock: 19,
    status: "ACTIVE",
    isFeatured: false,
    isNew: true,
    createdAt: new Date("2025-02-14"),
    updatedAt: new Date("2025-04-20"),
  },
  {
    id: "prod-6",
    name: "Parfum Signature No. 7",
    slug: "parfum-signature-no-7",
    description: "Eau de parfum boisée et florale, 75ml.",
    longDescription: `Conçu avec le maître parfumeur Julien Rassat, notre Signature No. 7 est une ode à la forêt de chênes après la pluie. Notes de tête : bergamote et poivre rose. Cœur : rose de mai et jasmin sauvage. Fond : vétiver, santal et ambre gris.`,
    price: 380,
    compareAtPrice: 480,
    images: [
      {
        id: "img-6-1",
        url: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&w=800&q=80",
        alt: "Parfum Signature No. 7",
        order: 0,
      },
    ],
    category: CATEGORIES[3],
    categoryId: "cat-4",
    variants: [
      {
        id: "var-6-1",
        name: "Contenance",
        value: "30ml",
        stock: 15,
        priceModifier: -150,
      },
      {
        id: "var-6-2",
        name: "Contenance",
        value: "75ml",
        stock: 20,
        priceModifier: 0,
      },
      {
        id: "var-6-3",
        name: "Contenance",
        value: "150ml",
        stock: 8,
        priceModifier: 200,
      },
    ],
    tags: ["parfum", "fragrance", "boisé", "floral", "promo"],
    rating: 4.8,
    reviewCount: 423,
    stock: 43,
    status: "ACTIVE",
    isFeatured: true,
    isNew: false,
    createdAt: new Date("2023-09-01"),
    updatedAt: new Date("2025-01-15"),
  },
  {
    id: "prod-7",
    name: "Ceinture Croco Embossée",
    slug: "ceinture-croco-embossee",
    description: "Ceinture en cuir de veau embossé crocodile, boucle laiton.",
    longDescription: `Réalisée en cuir de veau pleine fleur avec un embossage crocodile matte, cette ceinture est dotée d'une boucle en laiton doré massif. Un accessoire iconique de la maison LUMIÈRE.`,
    price: 520,
    compareAtPrice: undefined,
    images: [
      {
        id: "img-7-1",
        url: "https://images.unsplash.com/photo-1624222247344-550fb60fe8ff?auto=format&w=800&q=80",
        alt: "Ceinture croco",
        order: 0,
      },
    ],
    category: CATEGORIES[2],
    categoryId: "cat-3",
    variants: [
      {
        id: "var-7-1",
        name: "Taille",
        value: "80 cm",
        stock: 5,
        priceModifier: 0,
      },
      {
        id: "var-7-2",
        name: "Taille",
        value: "85 cm",
        stock: 7,
        priceModifier: 0,
      },
      {
        id: "var-7-3",
        name: "Taille",
        value: "90 cm",
        stock: 6,
        priceModifier: 0,
      },
      {
        id: "var-7-4",
        name: "Taille",
        value: "95 cm",
        stock: 3,
        priceModifier: 0,
      },
    ],
    tags: ["ceinture", "cuir", "croco", "accessoire"],
    rating: 4.5,
    reviewCount: 78,
    stock: 21,
    status: "ACTIVE",
    isFeatured: false,
    isNew: false,
    createdAt: new Date("2024-07-10"),
    updatedAt: new Date("2025-03-05"),
  },
  {
    id: "prod-8",
    name: "Écharpe Cachemire Alpin",
    slug: "echarpe-cachemire-alpin",
    description: "Écharpe en cachemire Grade A, finitions à la main.",
    longDescription: `Tissée en pur cachemire Grade A provenant des hauts plateaux de Mongolie, cette écharpe d'exception est bordée d'une frange à la main. Sa douceur incomparable et sa chaleur légère en font un indispensable de la garde-robe.`,
    price: 340,
    compareAtPrice: undefined,
    images: [
      {
        id: "img-8-1",
        url: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&w=800&q=80",
        alt: "Écharpe cachemire",
        order: 0,
      },
    ],
    category: CATEGORIES[3],
    categoryId: "cat-4",
    variants: [
      {
        id: "var-8-1",
        name: "Couleur",
        value: "Gris perle",
        stock: 12,
        priceModifier: 0,
      },
      {
        id: "var-8-2",
        name: "Couleur",
        value: "Camel",
        stock: 8,
        priceModifier: 0,
      },
      {
        id: "var-8-3",
        name: "Couleur",
        value: "Noir",
        stock: 10,
        priceModifier: 0,
      },
      {
        id: "var-8-4",
        name: "Couleur",
        value: "Bordeaux",
        stock: 5,
        priceModifier: 0,
      },
    ],
    tags: ["écharpe", "cachemire", "hiver", "tendance"],
    rating: 4.7,
    reviewCount: 201,
    stock: 35,
    status: "ACTIVE",
    isFeatured: false,
    isNew: false,
    createdAt: new Date("2024-10-01"),
    updatedAt: new Date("2025-01-20"),
  },
];

export const REVIEWS: Review[] = [
  {
    id: "rev-1",
    userId: "user-1",
    user: { id: "user-1", name: "Sophie Martin", image: undefined },
    productId: "prod-1",
    rating: 5,
    title: "Absolument magnifique",
    content:
      "Ce collier est d'une beauté époustouflante. La qualité de l'or et des diamants est irréprochable. La livraison était soignée et le packaging très luxueux. Je suis absolument ravie de mon achat.",
    verified: true,
    helpful: 47,
    createdAt: new Date("2025-03-15"),
  },
  {
    id: "rev-2",
    userId: "user-2",
    user: { id: "user-2", name: "Laurent Dubois", image: undefined },
    productId: "prod-1",
    rating: 5,
    title: "Cadeau parfait",
    content:
      "Offert à ma femme pour notre anniversaire. Elle est tombée amoureuse au premier regard. Le service client LUMIÈRE est aussi exceptionnel que les produits.",
    verified: true,
    helpful: 31,
    createdAt: new Date("2025-02-28"),
  },
  {
    id: "rev-3",
    userId: "user-3",
    user: { id: "user-3", name: "Amélie Chen", image: undefined },
    productId: "prod-1",
    rating: 4,
    title: "Très beau mais livraison un peu longue",
    content:
      "Le collier est magnifique, la qualité est au rendez-vous. La livraison a pris un peu plus de temps que prévu, mais le résultat vaut l'attente.",
    verified: true,
    helpful: 18,
    createdAt: new Date("2025-01-10"),
  },
];

export const REVENUE_DATA: RevenueData[] = [
  { month: "Jan", revenue: 45000, orders: 89 },
  { month: "Fév", revenue: 62000, orders: 124 },
  { month: "Mar", revenue: 58000, orders: 112 },
  { month: "Avr", revenue: 71000, orders: 138 },
  { month: "Mai", revenue: 88000, orders: 167 },
  { month: "Jun", revenue: 92000, orders: 178 },
  { month: "Jul", revenue: 76000, orders: 145 },
  { month: "Aoû", revenue: 83000, orders: 159 },
  { month: "Sep", revenue: 97000, orders: 186 },
  { month: "Oct", revenue: 110000, orders: 210 },
  { month: "Nov", revenue: 115000, orders: 224 },
  { month: "Déc", revenue: 128000, orders: 247 },
];

export const PROMO_CODES = [
  {
    code: "LUMIERE30",
    discountType: "percentage" as const,
    discountValue: 30,
    minOrderValue: 500,
  },
  {
    code: "BIENVENUE10",
    discountType: "percentage" as const,
    discountValue: 10,
    minOrderValue: 0,
  },
  {
    code: "LIVRAISON",
    discountType: "fixed" as const,
    discountValue: 15,
    minOrderValue: 100,
  },
];
