import type { Product, Category, Review, RevenueData } from '@/types'
export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    userId: 'user-1',
    user: { id: 'user-1', name: 'Sophie Martin', image: undefined },
    productId: 'prod-1',
    rating: 5,
    title: 'Absolument magnifique',
    content: 'Ce collier est d\'une beauté époustouflante. La qualité de l\'or et des diamants est irréprochable. La livraison était soignée et le packaging très luxueux. Je suis absolument ravie de mon achat.',
    verified: true,
    helpful: 47,
    createdAt: new Date('2025-03-15'),
  },
  {
    id: 'rev-2',
    userId: 'user-2',
    user: { id: 'user-2', name: 'Laurent Dubois', image: undefined },
    productId: 'prod-1',
    rating: 5,
    title: 'Cadeau parfait',
    content: 'Offert à ma femme pour notre anniversaire. Elle est tombée amoureuse au premier regard. Le service client LUMIÈRE est aussi exceptionnel que les produits.',
    verified: true,
    helpful: 31,
    createdAt: new Date('2025-02-28'),
  },
  {
    id: 'rev-3',
    userId: 'user-3',
    user: { id: 'user-3', name: 'Amélie Chen', image: undefined },
    productId: 'prod-1',
    rating: 4,
    title: 'Très beau mais livraison un peu longue',
    content: 'Le collier est magnifique, la qualité est au rendez-vous. La livraison a pris un peu plus de temps que prévu, mais le résultat vaut l\'attente.',
    verified: true,
    helpful: 18,
    createdAt: new Date('2025-01-10'),
  },
]